version: '3'
services:
  go-api:
    build: ./go
    volumes:
      - ./go:/go
    ports:
      - "8000:8000"
  proxy:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - go-api