version: '3'
services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
  go-api:
    build: ./go
    volumes:
      - ./go:/go
    ports:
      - "8000:8000"
    depends_on:
      - db
  c-api: 
    build: ./c
    volumes:
      - ./c:/c
    ports:
      - "8001:8001"
    depends_on:
      - db
  proxy:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - go-api
      - c-api
volumes:
  dbdata:

